### ISSUE TITLE
version 4 not available on pypi

### ISSUE THREAD

**Issue by cannatag** [reahl/reahl#115]
Hi, I'm trying to follow the tutorial on https://www.reahl.org/docs/4.0/tutorial/ but when I try to install reahl from pypi I get the 3.2 version and I don't find the tutorial examples.

How can I get version 4 of reahl?

**Comment by craig-reahl** [comment]
Hi, thanks for taking the time to let us know.

Apologies for that - you have caught us out! The great news is that we decided to released the new version (4.0.0) moments ago. However we ran into a deployment issue, thus the packages are not yet on PyPI, however, our new website released. We are busy looking at it and should have it ready soon.

Craig.

**Comment by cannatag** [comment]
Sorry for bothering you! I read about Reahl and just wanted to give it a try. It looks such a professional framework to work with. I started the tutorial just a few hours ago, I will wait for the deployement on PyPI.

Thanks for your prompt response and great work!

**Comment by craig-reahl** [comment]
No problem at all!
Sadly it seems it will take a bit longer to deploy to PyPI than I initially thought and will keep you updated.

We love Reahl too, so much that [www.reahl.org](www.reahl.org) actually runs on it! (however,reahl wasn't installed from PyPI were the www.reahl.org website is located)

**Comment by IwanVosloo** [comment]
Thanks for your patience. I have managed to get the release to go through to PyPI now. (We hit some snags with the new PyPI and our infrastructure - they are resolved now.)
