### ISSUE TITLE
ValueError: path must be None of list of paths to look for modules in

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#137]
When attempting to follow[ the instructions to run tutorial.hello ](https://www.reahl.org/docs/4.0/tutorial/gettingstarted-examples.d.html)  I get the following error trace:

```
c:\Temp>reahl example tutorial.hello
REAHLWORKSPACE environment variable not set, defaulting to C:\Users\i2615
Checking out to c:\Temp\hello
c:\Temp\hello\.reahlalias
c:\Temp\hello\.reahlproject
c:\Temp\hello\hello.py
c:\Temp\hello\etc\web.config.py

c:\Temp>cd hello

c:\Temp\hello>reahl setup -- develop -N
REAHLWORKSPACE environment variable not set, defaulting to C:\Users\i2615
Traceback (most recent call last):
  File "c:\development\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\development\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Development\Scripts\reahl.exe\__main__.py", line 9, in <module>
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 208, in execute_one
    result = cls().do(sys.argv[1:])
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 234, in execute
    return super(ReahlCommandline, self).execute(args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 169, in execute
    return command.do(args.command_args)
  File "c:\development\lib\site-packages\reahl\component\shelltools.py", line 110, in do
    return self.execute(args)
  File "c:\development\lib\site-packages\reahl\dev\devshell.py", line 281, in execute
    results[i] = self.execute_one(i, args)
  File "c:\development\lib\site-packages\reahl\dev\devshell.py", line 223, in execute_one
    retcode = self.function(project, args)
  File "c:\development\lib\site-packages\reahl\dev\devshell.py", line 402, in function
    project.setup(args.setup_py_args, script_name='%s %s' % (sys.argv[0], self.keyword))
  File "c:\development\lib\site-packages\reahl\dev\devdomain.py", line 1719, in setup
    py_modules=self.py_modules_for_setup(),
  File "c:\development\lib\site-packages\reahl\dev\devdomain.py", line 1814, in py_modules_for_setup
    return list(set([i[1] for i in pkgutil.iter_modules('.') if not i[2]])-{'setup'})
  File "c:\development\lib\site-packages\reahl\dev\devdomain.py", line 1814, in <listcomp>
    return list(set([i[1] for i in pkgutil.iter_modules('.') if not i[2]])-{'setup'})
  File "c:\development\lib\pkgutil.py", line 123, in iter_modules
    raise ValueError("path must be None or list of paths to look for "
ValueError: path must be None or list of paths to look for modules in

c:\Temp\hello>

```

**Comment by metaperl** [comment]
I figured out what the problem is. On [line 1814](https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L1814) of devdomain.py we see this:

        return list(set([i[1] for i in pkgutil.iter_modules('.') if not i[2]])-{'setup'})

I.e., we are passing a string to `pkgutil.iter_modules()` but that code throws an error when a string is passed to it:

```python

    elif isinstance(path, str):
        raise ValueError("path must be None or list of paths to look for "
                        "modules in")
```

**Comment by metaperl** [comment]
It works if you pass `['.']` instead of just `'.'` -

        return list(set([i[1] for i in pkgutil.iter_modules(['.']) if not i[2]])-{'setup'})

I would supply a patch but I do not have git setup here at work yet.

**Comment by metaperl** [comment]
OK I was able to fork the repo and edit the code - https://github.com/reahl/reahl/pull/139

**Comment by IwanVosloo** [comment]
Fantastic, thank you. Will work more carefully through your issues when I get home!

**Comment by IwanVosloo** [comment]
(BTW, I see you are on WIndows. We don't develop on Windows, so it will be interesting to see what needs to be fixed on that platform.)

**Comment by metaperl** [comment]
The 4.0.4 release to PyPi still fails with this error. When will [this patch](https://github.com/reahl/reahl/commit/e232dd3f7b2e05221f6ef99b982b740450d822f7#diff-5544986386ed541f83c7f25f9933068d) be integrated into a public release so that I do not have to manually patch the releases I download from PyPi?

**Comment by IwanVosloo** [comment]
That does not sound right. Something else must be happening here that we don't understand. Are you dead sure you have successfully upgraded everything[ by creating a new virtualenv and installing new all the new versions of the reahl components](https://www.reahl.org/docs/4.0/whatchanged.d.html?highlight=upgrade)?

The current code shows that the patch has been applied:
https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L1820

As does the merged pull request: https://github.com/reahl/reahl/commit/4b06026cca7edeee1fd95a3b9b4c49069e9c5d4e

Can you post the output of pip freeze where you are experiencing the problem?

**Comment by Foadsf** [comment]
Hey folks, I am having the same error [here](https://stackoverflow.com/q/68938983/4999991), but not sure how relevant it is to the above discussion.

**Comment by IwanVosloo** [comment]
Hi @Foadsf, our issue was that instead of passing a list of strings to pkg_util.iter_modules, we passed only a single string. Fixing that solved the issue for us as per https://github.com/reahl/reahl/commit/4b06026cca7edeee1fd95a3b9b4c49069e9c5d4e.
