### ISSUE TITLE
add_panel not documented and breaks the convention of using add_child

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#138]
In [the presentation](https://youtu.be/xjKRJHaRQ0Y?t=515) we see a call to `add_panel` which begs the question: what is the difference between add_panel and add_child? 

Next, `add_panel` is not in [the documentation](https://www.reahl.org/docs/4.0/genindex.d.html#A) so how are we supposed to understand it?

**Comment by IwanVosloo** [comment]
That presentation is a bit old, and applies to an older version of Reahl, it is documented here: https://www.reahl.org/docs/2.1/web/ui.d.html#tabbed-or-sliding-panels 

add_panel was specific to creating a tabbed panel in that version.

This stuff was replaced with bootstrap-based Carousel: https://www.reahl.org/docs/4.0/web/bootstrap/carousel.d.html
