### ISSUE TITLE
Provide an inheritance hierarchy of ui widgets

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#140]
[pyreverse](https://www.logilab.org/blogentry/6883) is part of [pylint](https://www.logilab.org/project/pylint). You can generate a graphviz dot representation of a module via:

    pyreverse -o dot ui

You can then paste the dot representation into [a graphviz online tool ](https://dreampuf.github.io/GraphvizOnline/)to generate a png

![reahl-ui-classes](https://user-images.githubusercontent.com/21293/47240291-1cbccd00-d3a5-11e8-9c6d-2aea86c9725a.png)

**Comment by craig-reahl** [comment]
Great, thanks, that looks impressive ! 

We usually create PlantUML (puml) kind of files that gets imported into our documentation. We hand craft these so as to provide a personal touch to the concept we need to explain.

Example [from here](https://github.com/reahl/reahl/blob/master/reahl-web/reahl/web_dev/inputandvalidation/user_events_and_assosiated_input_handling.puml):
![user_events_and_assosiated_input_handling](https://user-images.githubusercontent.com/10047770/47253348-a3c77f00-d451-11e8-9ca0-a3cc9119015a.png)

Thanks again, appreciate your contribution.

Craig.

**Comment by IwanVosloo** [comment]
Yup, to elaborate:

Diagrams are important tools to convey insight into a domain. Key to doing that is to only put relevant details on a diagram. Auto-generating things cannot give you that. That is why we prefer to draw specific diagrams.

The question is: which ones did we miss, what would be useful, and where in the docs should be link to these? 

There can be a few diagrams relating to UI Widgets. How Inputs work, for example is quite intricate.

Like the example above, I think most of these pics are in reference docs or in our _dev directories. (See https://www.reahl.org/docs/4.0/devmanual/sourcecode.d.html#making-sense-of-code if you want to know where to find these).
