### ISSUE TITLE
get_edit_bookmark not indexed or documented?

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#147]
`get_edit_bookmark`  is not in the [index](https://www.reahl.org/docs/4.0/genindex.d.html#G)

**Comment by craig-reahl** [comment]
Thanks, we did not see the need to document it, thus it did not make it to the code reference index. 
Would you prefer to have all methods  referenced in the code index, or do you think it will then be too cluttered?

**Comment by IwanVosloo** [comment]
Mmm, this one had me confused.

I see def get_edit_bookmark is part of the datatablebootstrap example code itself.

That's why its not documented. Perhaps we should mention it in the example text?
