### ISSUE TITLE
verbose flag to `reahl migratedb $CONFIG_DIRECTORY`

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#148]
Do I need to know something or setup something to run a db migration? I added a new SQLAlchemy class to my program, and then ran `reahl migratedb etc` but it did not add the new SQLAlchemy class.

I then also added it to persisted in `.reahlproject` but that did not help.

It would be nice if the migration process had a debug mode that was very verbose about what it found and what it decides and what it did.

**Comment by craig-reahl** [comment]
1. For the verbosity, you can set 

You could add this to your `etc/reahl.config.py`:

```
    from reahl.sqlalchemysupport import SqlAlchemyControl
    reahlsystem.orm_control = SqlAlchemyControl(echo=True)
```
We could perhaps chat about what more you would need.


2. On initial project setup, you can use:

reahl createdbtables etc/

and 

reahl dropdbtables etc/


Thereafter you have to [write a migration](https://www.reahl.org/docs/4.0/tutorial/schemaevolution.d.html#migration-basics) if you do not want to recreate the project database from scratch by using the `dropdbtables` and  `createdbtables `which only needs the persisted classes defined in your `.reahlproject`. 

> Create a Migration subclass for each change that needs to be made to the schema (and perhaps data) of the previous version.
> ...
> Register all your Migrations in the .reahlproject file

**Comment by IwanVosloo** [comment]
You can get more info when ANY reahl xxx command is run by setting a different log level. This is especially useful when you do run migrations:

`reahl -l INFO migratedb etc`

Here is some example output (which finds no migrations that need to run):

```INFO:reahl.component.config:Using config in reahl-web/etc
WARNING:reahl.component.config:reahlsystem.debug in reahl-web/etc/reahl.config.py is using a dangerous default setting: True
WARNING:reahl.component.config:web.default_http_port in reahl-web/etc/web.config.py is using a dangerous default setting: 8000
WARNING:reahl.component.config:web.encrypted_http_port in reahl-web/etc/web.config.py is using a dangerous default setting: 8363
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:reahl.component.migration:Scheduling 0 upgrade migrations for reahl-component - from version 4.1 to 4.1
INFO:reahl.component.migration:Scheduling 0 upgrade migrations for reahl-web - from version 4.1 to 4.1
INFO:reahl.component.migration:Scheduling 0 upgrade_cleanup migrations for reahl-web - from version 4.1 to 4.1
INFO:reahl.component.migration:Scheduling 0 upgrade_cleanup migrations for reahl-component - from version 4.1 to 4.1
INFO:reahl.component.migration:Scheduling 0 schedule_upgrades migrations for reahl-web - from version 4.1 to 4.1
INFO:reahl.component.migration:Scheduling 0 schedule_upgrades migrations for reahl-component - from version 4.1 to 4.1
INFO:reahl.component.migration:Executing schema change phase drop_fk
INFO:reahl.component.migration:Executing schema change phase drop_pk
INFO:reahl.component.migration:Executing schema change phase pre_alter
INFO:reahl.component.migration:Executing schema change phase alter
INFO:reahl.component.migration:Executing schema change phase create_pk
INFO:reahl.component.migration:Executing schema change phase indexes
INFO:reahl.component.migration:Executing schema change phase data
INFO:reahl.component.migration:Executing schema change phase create_fk
INFO:reahl.component.migration:Executing schema change phase cleanup
```

Note that migrations are not always run. Each migration has a version number associated with it, so it will only be run if its version is newer than the version of your project (as is automatically recorded in the database)

On sqlite you can see this info with:

`select * from reahl_schema_version ;`
