### ISSUE TITLE
Provide github wiki access

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#151]
I want to make some notes about role-based authorization in the wiki for Reahl. Should we enable  it?

**Comment by IwanVosloo** [comment]
We can... I am a bit nervous about starting something like a wiki if it won't grow and be maintained, but I guess you have to start somewhere!

We also have climbed a bit of a learning curve regarding documentation, and currently try to follow Danielle's guidance as per this talk: https://youtu.be/qK-AnF5FJTs?t=379

How can the wiki fit into that?

**Comment by metaperl** [comment]
> How can the wiki fit into that?

For me, I would say reference. Right now, I want to browse all the Plant UML diagrams and I have to manually go and find them all and put them somewhere for viewing... they should be available for browsing somehow, if not the wiki.

**Comment by IwanVosloo** [comment]
If we miss reference documentation, we should add to the docs in reahl-doc.
And yes, the plantuml diagrams can help a lot there.

The wiki itself might be a starting point for "how to" docs.

I have added  #177 for adding more diagrams to reference docs. I suggest we handle missing things in docs each on its own merit (started tagging these now with "documentation").
