### ISSUE TITLE
`reahl build` requires GNUPG to be installed. 

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#152]
hello, at work I do not have the `gpg` binary installed and could not download and install any of the ones listed at [the GNU Pg site](https://gnupg.org/download/).

Commenting out [line 204](https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L204)
    self.project.distribution_egg_repository.sign_files_for(self)

seemed to create an installable wheel.

So my questions are:
1. Should `reahl build` have a `--nosign` option to make GPG signing optional?
2. Would it be acceptable to do the encryption with [a Python-only implementation of the Open GPG standard](https://www.google.com/search?q=python+only+implementation+of+the+OpenPGP+standard&rlz=1C1GCEA_enUS781US781&oq=python+only+implementation+of+the+OpenPGP+standard&aqs=chrome..69i57.3615j0j4&sourceid=chrome&ie=UTF-8)?

**Comment by metaperl** [comment]
[PGPy](https://github.com/SecurityInnovation/PGPy/) seems a viable choice for a Python-only encryption.

**Comment by IwanVosloo** [comment]
Adding a --nosign option is easy to do, I think we can do that without much thinking.

Using a python package is cool too - just a tiny bit more effort. We also have to make sure licenses are compatible with the GPL and allows us to dual-license. And we need to make sure its a project that is going to stay the course. Not big things...just mentioning the non-obvious that is involved.

**Comment by IwanVosloo** [comment]
A shallow search of python gnupg packages yielded that these typically also require the gpg binaries to be installed. PGPy seems to be the only viable one - yet it seems a bit quiet. 

Also, I we have some concerns to using a gpg implementation that is not as well scrutinised as the official gpg programs. 

So, I think best option is to just implement the --nosign option.

**Comment by craig-reahl** [comment]
`reahl build --nosign`
