### ISSUE TITLE
os.path.expanduser('~') is more platform-independent than os.environ['HOME']

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#159]
As is clear from [the docs on os.path.expanduser('~')](https://docs.python.org/3.0/library/os.path.html#os.path.expanduser), this function does a more thorough job of locating the home directory of the person operation the reahl command line program.

**Comment by IwanVosloo** [comment]
Yup, true. What issue did this cause for you?

**Comment by metaperl** [comment]
I cant remember. But `HOME` is not defined on Windows by default. so
anywhere that Reahl tries to find `HOME` it will fail on Windows.

**Comment by IwanVosloo** [comment]
I find this only in the config of some examples. It would be nice to have the consequences penned here so that people searching for help on an issue might find it.

Marking this as a bug anyway so we can fix those example configs.
