### ISSUE TITLE
Is there pre-baked logout functionality

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#163]
In looking over [AccountUI](https://www.reahl.org/docs/4.0/domain/systemaccountui.d.html#reahl.domainui.bootstrap.accounts.AccountUI), I do not see a path provided for logging a user out. How does one add this functionality to a reahl webapp?

**Comment by IwanVosloo** [comment]
We did not think that warranted an actual page, but that you'd rather want to put a Button that will trigger the AccountManagementInterface's  `log_out_event` (see https://www.reahl.org/docs/4.0/domain/systemaccountmodel.d.html?highlight=log_out_event ).

An example of this is in the access control example: https://www.reahl.org/docs/4.0/tutorial/accesscontrol.d.html 

See specifically its LogoutForm.

**Comment by metaperl** [comment]
I agree that it does not warrant a page. But if you take a look at most
sites you will see that the logout functionality is provided by an anchor
tag not a button.

**Comment by IwanVosloo** [comment]
We make a strict distinction between Buttons and Anchors. Buttons submit, and are tied to Events and Actions. Anchors just take you to another URL.

You can make an Anchor look like a Button using a ButtonLayout. You can also make a Button look like an Anchor, but we have not exposed something like that in a Layout, see [Bootstrap's documentation](https://getbootstrap.com/docs/4.0/components/buttons/).

**Comment by metaperl** [comment]
>  a Button that will trigger the AccountManagementInterface's log_out_event

It seems that this `log_out` event
1. Logs out and returns to`/accounts/login` 
1. appends a `returnTo` query parameter which causes the app to return to the same URL in the app that the user was on when he pressed logout. 

Is there anyway to have a log out event that returns to a specified URL (in my case, `Home`) and does not append the `returnTo` query parameter?

**Comment by IwanVosloo** [comment]
`log_out_event` is not used anywhere except where you are using it, so it is not causing the behaviour you are experiencing. I suspect it is caused by staying on the same page, which requires a login.

You can use [a target kwarg to your call to define_event_handler](https://www.reahl.org/docs/4.0/web/fw.d.html?highlight=define_event_handler#reahl.web.fw.Widget.define_event_handler)
