### ISSUE TITLE
Each tutorial should use a different database name

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#167]
I'm willing to supply this fix, but want to make sure the authors of Reahl agree.

Each of [the tutorial examples](https://github.com/reahl/reahl/tree/master/reahl-doc/reahl/doc/examples/tutorial) should use a different database.

This makes it easier to run each app without having to run `reahl dropdb etc` before each app.

**Comment by metaperl** [comment]
If my proposed patch is accepted then [this documentation](https://www.reahl.org/docs/4.0/tutorial/gettingstarted-examples.d.html) will need to be fixed because it currently says "All examples use the same database. Before you run a different example, you need to remove the previous database:"

**Comment by IwanVosloo** [comment]
I hear your issue..., but we've also been trying to make all the tutorials as similar a possible, so I'd be loathe to use different names.

I wonder is there is not another plan. One might be to put the database, in the current directory (which would be the root of the example). That will keep examples consistent.

What's odd about this idea is that the DB file will be next to your source code.

What will also happen is that the webserver will keep restarting when the DB changes unless you exclude it, say in https://github.com/reahl/reahl/blob/master/reahl-webdev/reahl/webdev/webserver.py#L370

Any other options?

**Comment by metaperl** [comment]
> we've also been trying to make all the tutorials as similar a possible

Why not make them as realistic as possible? Would you name your database `reahl.db` for an application that serves to add email and name to a database?

>  One might be to put the database, in the current directory 

This is already possible via the `REAHLWORKSPACE` environmental variable I think.

> What will also happen is that the webserver will keep restarting when the DB changes unless you exclude it

I wasnt aware of that ramification. 

But if you think about it, one of the ultimate tests of a framework is the ability to plug in and mount all the apps within another meta-application. If all of these apps use the same database, such a meta-application will fail.

**Comment by metaperl** [comment]
For instance, here is [the Nagare applications portal](http://www.nagare.org/portal/) where all of these independent apps got mounted within a meta-application with no need for code modifications.

Flask has the concept of blueprints for a similar purpose.

Does Reahl pass the "mountability" test?

**Comment by metaperl** [comment]
Is there a method to get the name of the current app? Here is what I propose be added to each tutorial:

```python

from __future__ import print_function, unicode_literals, absolute_import, division
import os

APP = 'sessionscopebootstrap' # Calculate this via a method call

# In production this has to be set, to the name of the egg of your application:
reahlsystem.root_egg = APP
reahlsystem.debug = False

# If using SQLite:
reahlsystem.connection_uri = 'sqlite:///{}/{}.db'.format(
    os.path.expanduser('~'), APP)

# If using MySql:
# reahlsystem.connection_uri = 'mysql://myname:mydatabasepassword@myname.mysql.pythonanywhere-services.com/helloanywhere'

# If using PostgreSQL:
#reahlsystem.connection_uri = 'postgresql://myname:mydatabasepassword@myname-somenumber.postgres.pythonanywhere-services.com/helloanywhere'

```

**Comment by IwanVosloo** [comment]
The default connection URI is set up here: https://github.com/reahl/reahl/blob/master/reahl-component/reahl/component/config.py#L231

**Comment by IwanVosloo** [comment]
We can do something to set the default so that they don't clash. Defaults are chosen so examples can work with as little config as possible - I don't want to add configs to examples everywhere.

**Comment by IwanVosloo** [comment]
The relevant code is in class scope, so we can't determine from the config what the app name is. However, we can use as default for the db name the name of the current directory (as is done for the default of reahlsystem.root_egg anyway). This would make the name of the DB and the name of the app "the same" but only perchance because they happen to both default to the name of the current directory. This can be confusing....

The other option is to just put the reahl.db in the current directory (ie, the root of the example project). This will mean though that we'll have to prevent it from restarting the webserver when it changes in  https://github.com/reahl/reahl/blob/master/reahl-webdev/reahl/webdev/webserver.py#L370.

Leaving this here with the TODO: the last option.

**Comment by metaperl** [comment]
> The relevant code is in class scope, so we can't determine from the config what the app name is.

Perhaps with Inversion of Control or Dependency Injection it would be possible?

> This will mean though that we'll have to prevent it from restarting the webserver when it changes

Right.

Bottom line for me is this:

# Quickly switch between apps

If I'm demoing a bunch of apps for someone, I want to be able to change to that directory and type `reahl serve etc` and have it run. I do not want to undo what some other completely irrelevant app has done. And I do not want to re-create my steps to set this one up because some other app clobbered my handiwork.

# Mountable apps

For Reahl to prove itself as an Python-only framework, it must show it can do whatever Nagare (the other Python-only framework) can do. [Here](http://www.nagare.org/portal/) you can see Nagare mounting apps within a container app with no code changes needed to any of the apps.

The first stumbling block for Reahl is this ticket - the same database is being used for all the examples. 

# Sound Engineering

A database name that is specific to the application is sound engineering practice. A generic name such as `reahl.db` conveys nothing.

**Comment by IwanVosloo** [comment]
> Perhaps with Inversion of Control or Dependency Injection it would be possible?

That mechanism allows one to set a config value, not to specify what it is or what its default is. Sure, you could write code in there to accomplish this, but it would be a confusing hack. There should be one and only one way to specify what config setting you have and what their defaults are.

I think our solution above would accomplish your main goal and I think that is an important improvement.

Mountable apps that each sit on its own DB is not a design goal for us. We have mountable [UserInterfaces](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html) , each of which (or a collection of which) can be distributed in its own "component" (aka wheel). You can assemble an application by mixing all of these together on a single database, also without code changes to any of them. We have a lot of infrastructure to make this possible, including the [migration](https://www.reahl.org/docs/4.0/tutorial/schemaevolution.d.html) of a database that underlies a collection of such components. 

> A database name that is specific to the application is sound engineering practice. A generic name such as reahl.db conveys nothing.

Yes, you're right. But in a tiny example...is this really the important thing to worry about? We could rename it to ./example.db as part of this change.

**Comment by metaperl** [comment]
> I think our solution above would accomplish your main goal and I think that is an important improvement.

If you mean the solution where each database is in the root directory of each example project, I think this is a great step forward.

> But in a tiny example...is this really the important thing to worry about? 

It depends on how you think... something named `reahl.db` looks like something that reahl is using for its internal housekeeping. `addressbook.db` is a clear statement about the purpose of the database. 

But as long as the databases get moved to the root of the example directory, that is a great step forwards. The rename to `example.db` is still suffering from being too general. Dont waste time with such a rename.

**Comment by IwanVosloo** [comment]
Yup, we'll do that. It seems to be a good balance of addressing the need yet staying simple.

**Comment by IwanVosloo** [comment]
BTW, we ended up adding a mechanism to be able to make one config setting dependent on another.
