### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#169]
In reahl\component\modelinterface.py on line 1094 we see:

    if not isinstance(check, AdaptedMethod) and isinstance(check, collections.Callable):

and this line throws the warning: 

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by IwanVosloo** [comment]
Ok, thanks, lets treat it as a bug. We have to just be careful to maintain Py27 compatibility.

On what version of Python are you running this?

**Comment by IwanVosloo** [comment]
Done in pull request #172
