### ISSUE TITLE
Running a project from a directory does not imply you are in production

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#174]
Currently [we see](https://github.com/reahl/reahl/blob/master/reahl-web/reahl/web/fw.py#L2585) 

```python
    @classmethod
    def from_directory(cls, directory):
        """Create a ReahlWSGIApplication given the `directory` where its configuration is stored."""
        config = StoredConfiguration(directory, in_production=True)
        config.configure()
        return cls(config)
```

with no option for `in_production` to be false, which it is for me at the moment. I might be deploying something somewhere that mimics production, but that does not mean that I am in production.

**Comment by IwanVosloo** [comment]
In all our use cases this is only used in prod, since using the 'reahl serve' or our test infrastructure do not use this method.

Happy to add a kwarg for it though, to make it more flexible.

How are you using it?

**Comment by IwanVosloo** [comment]
Ok, looking at your AWS-related issues, I get this now. 

You are running something on AWS, in a staging environment.

The `in_production` here is perhaps not named well. It just means break when required config settings are not set or dangerous defaults have not been explicitly set.

I think we should rename the `in_production` kwarg to "strict_validation=True", and add it to the signature of from_directory.

**Comment by IwanVosloo** [comment]
Lets add the strict_validation kwarg in 4.1, deprecating the in_production kwarg, to be removed in 5.1
