### ISSUE TITLE
Create sample data for Security and access control example

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#176]
I tried to create users and their related address books for the Security and access control example. 

I had no problem creating sample users, but when I attempted to create a single address book for each user, I ran into a number of issues:

1. First I was not sure where to put the `sample_data` code so that it would fire only once and not be called multiple times as the user interface rendered itself.
1. Next, I was getting relational integrity errors.

If you could provide a suggestion and/or patch to the code base which creates about 5 sample users and their associated addressbooks, then I could play with this example and adapt it to our use case internally.  I'm also not sure where to put such code. An [earlier example](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html) had a `reahl demosetup` command, but there is no such thing for this code. 

so it seems like the most thorough way to add sample data is to:
1. add a new command to reahl for this example
1. add the sample data code there

Here is my current `sample_data` code:
```python

def sample_data():
    password = 'topsecret'

    def new_account(email):
        account = EmailAndPasswordSystemAccount(email=email)
        Session.add(account)
        account.set_new_password(account.email, password)
        account.activate()
        return account

    for c in 'a b c d e'.split():
        email = '{}@{}.com'.format(c,c)
        acct = new_account(email)
        print("New account = {}... id = {}".format(acct, acct.id))
        Session.add(AddressBook(owner_id=acct.id))

```

**Comment by IwanVosloo** [comment]
There is a `reahl demosetup` for the [Security and access control example](https://www.reahl.org/docs/4.0/tutorial/accesscontrol.d.html) but it is not documented.


demosetup is an alias: `reahl help-commands | grep demosetup` will show:
  ```
    demosetup  "setup -- -q pytest --addopts '-s -o python_functions=demo_setup  --pyargs accessbootstrap_dev'"
  ```

So, the demo_setup function in there should tell you all you need to know to create users.

The setup code is here: https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/accessbootstrap/accessbootstrap_dev/test_accessbootstrap.py#L56

All users created have the password "topsecret". The one user (johndoe@some.org) has various levels of access to the address books of others, the details present in this code (see esp the last 3 lines):

```
    john = access_domain_fixture.account
    jane = access_domain_fixture.new_account(email='janedoe@some.org')
    jane_book = access_domain_fixture.new_address_book(owner=jane)
    someone = access_domain_fixture.new_account(email='someone@some.org')
    someone_book = access_domain_fixture.new_address_book(owner=someone)
    someone_else = access_domain_fixture.new_account(email='someoneelse@some.org')
    someone_else_book = access_domain_fixture.new_address_book(owner=someone_else)

    jane_book.allow(john, can_add_addresses=True, can_edit_addresses=True)
    someone_book.allow(john, can_add_addresses=False, can_edit_addresses=True)
    someone_else_book.allow(john, can_add_addresses=False, can_edit_addresses=False)
```

I am leaving this item here as a TODO to add some details about the demosetup command and the users created to that tutorial's documentation.

**Comment by metaperl** [comment]
One line in `demo_setup()` is kind of odd:

    access_domain_fixture.address_book
   
this line appears to access something. But it does not assign what it access to anything.

Also, this line:

    john = access_domain_fixture.account

Somehow this works without a call to `new_account()`

**Comment by IwanVosloo** [comment]
Thats correct.

AccessDomainFixture is a [tofu.Fixture](https://www.reahl.org/docs/4.0/devtools/tofu.d.html), so `.address_book` will invoke `.new_address_book()` and store the result in `.address_book` so that if you call it subsequently you will always get "the address book of that fixture" back.

Some more relevant info here: https://www.reahl.org/docs/4.0/devmanual/testing.d.html

In this cases we just need to access it to trigger the first call to `.new_address_book`
