### ISSUE TITLE
What version constitutes the genesis version if an app was created with no version metadata?

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#180]
[The .reahlproject file for datatablebootstrap](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/datatablebootstrap/.reahlproject) does not have any metadata about it's version.

If one were to write database migrations, we would need to add this section.... should this section be a required part of all apps? And should a sanity check require this section?

At any rate, the project version number can start with any decimal number as long as subsequent versions increase this number?

**Comment by IwanVosloo** [comment]
By default, any project has hardcoded metadata if you don't specify anything. This is an instance of [ProjectMetadata](https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L906) in which the initial version is shown as 0.0.

I think what we perhaps need to do here is:
 - add some documentation about this somewhere; and
 - output more information (such as version number) as part of `reahl info`.

> should this section be a required part of all apps? And should a sanity check require this section?

I'd rather not - it helps keep examples as thin as possible.

> And should a sanity check require this section?

We could add a check that warns you, similar to the DangerousDefaults. I am not sure how or when to trigger the check though, will have to dig into that. Also need to assess how much value it would add...

> At any rate, the project version number can start with any decimal number as long as subsequent versions increase this number?

Yes, see the regex used in [Version](https://github.com/reahl/reahl/blob/master/reahl-dev/reahl/dev/devdomain.py#L570)

Lets add some docs to these places to clarify that: 
 - https://www.reahl.org/docs/4.0/tutorial/schemaevolution.d.html
 - https://www.reahl.org/docs/4.0/devtools/xmlref.d.html#development-and-packaging

I think a section is also needed under https://www.reahl.org/docs/4.0/devtools/index.d.html to explain the building/uploading/packaging

**Comment by IwanVosloo** [comment]
(I see there is a mention of `reahl build` in https://www.reahl.org/docs/4.0/tutorial/deployment.d.html#build-and-upload-the-helloanywhere-example)
