### ISSUE TITLE
Clarifying the docs on the Schema Evolution tutorial

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#181]
[The tutorial on schema evolution](https://www.reahl.org/docs/4.0/tutorial/schemaevolution.d.html), states:

> edit the .reahlproject file and increase the version of the component to 0.1

I see [the .reahl project file](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/migrationexamplebootstrap/.reahlproject) however:

* "the component" is vague. What component? There is no mention of component prior to this point in this document, making it impossible to know what you are talking about.
* What would the file look like after we " increase the version of the component to 0.1"?
* Finally, it appears that there is a required syntax for the version?

Actually, I'm starting to see the light: "the component" is the entire project. And the version number to increase is [the first item in the metadata](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/migrationexamplebootstrap/.reahlproject#L3), correct?

Next we read:

To simulate installing the newer version, run:

    reahl setup -- develop -N

After installing a new version of your component, run the following in order to migrate the old database:

    reahl migratedb etc

The question becomes, does `reahl setup -- develop -N` install a new version of my component? If so, then I would suggest the phrase "After installing a new version of your component" be changed to "Now that a new version of your component has been installed." If there are more steps to "installing a new version of your component", then please link to them.

Final question: unlike the tutorial examples that have just an `etc` directory, I have two directories, one for dev and one for production. I have just successfully done a `reahl migratedb dev` but may want to do 4 or 5 more database deltas as documented before doing anything to production. Is it possible to make numerous deltas in my `dev` environment and then a single `reahl migratedb production` and have it apply all of the deltas in succession?

**Comment by IwanVosloo** [comment]
I don't know why, but this one slipped past us undetected....

We can polish the docs for this tutorial a bit as you suggest.

> Actually, I'm starting to see the light: "the component" is the entire project. And the version number to 
increase is the first item in the metadata, correct?

Thats correct.

> The question becomes, does reahl setup -- develop -N install a new version of my component? 

See also our explanation of "component" and `setup develop` in [the hello world tutorial](https://www.reahl.org/docs/4.0/tutorial/gettingstarted-develop.d.html#preparing-for-development).

It updates your project's metadata, just like `python setup.py develop` would do, hence is equivalent to installing your component in-place as having a new version.

>  Is it possible to make numerous deltas in my dev environment and then a single reahl migratedb production and have it apply all of the deltas in succession?

I don't understand what you mean by `delta` here. If it is "a change to the database schema", then, yes. You need not have created a simple AddDate Migration as was done in this example. Your Migration should just be a logical change. That can be something like "rearrange how we store users and passwords" or whatever, which in turn can comprise of a number of changes to the schema. That is what's done in the Migration's schedule_upgrades method. Each change to the DB is scheduled as part of the single Migration.

You CAN also list more than one Migration for the same version.
