### ISSUE TITLE
reahl.component.shelltools.ExecutableNotInstalledException: Executable not found: dropdb

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#183]
(reahl_env) c:\appserv\water_poll>pytest -o python_functions=demo_setup --pyargs water_poll_dev.test_water_poll
pytest -o python_functions=demo_setup --pyargs water_poll_dev.test_water_poll
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.9.3, py-1.7.0, pluggy-0.8.0
rootdir: c:\appserv\water_poll, inifile:
collected 1 item

water_poll_dev\test_water_poll.py F                                    [100%]

================================== FAILURES ===================================
________ demo_setup[sql_alchemy_fixture0-water_poll_domain_fixture0] _________

self = <FunctionWrapper at 0x366b4c8 for function at 0x33e4c00>, args = ()
kwargs = {'water_poll_domain_fixture': WaterPollDomainFixture[default_scenario], 'sql_alchemy_fixture': SqlAlchemyFixture[default_scenario]}
instance = None

    def __call__(self, *args, **kwargs):
        # If enabled has been specified, then evaluate it at this point
        # and if the wrapper is not to be executed, then simply return
        # the bound function rather than a bound wrapper for the bound
        # function. When evaluating enabled, if it is callable we call
        # it, otherwise we evaluate it as a boolean.
    
        if self._self_enabled is not None:
            if callable(self._self_enabled):
                if not self._self_enabled():
                    return self.__wrapped__(*args, **kwargs)
            elif not self._self_enabled:
                return self.__wrapped__(*args, **kwargs)
    
        # This can occur where initial function wrapper was applied to
        # a function that was already bound to an instance. In that case
        # we want to extract the instance from the function and use it.
    
        if self._self_binding == 'function':
            if self._self_instance is None:
                instance = getattr(self.__wrapped__, '__self__', None)
                if instance is not None:
                    return self._self_wrapper(self.__wrapped__, instance,
                            args, kwargs)
    
        # This is generally invoked when the wrapped function is being
        # called as a normal function and is not bound to a class as an
        # instance method. This is also invoked in the case where the
        # wrapped function was a method, but this wrapper was in turn
        # wrapped using the staticmethod decorator.
    
        return self._self_wrapper(self.__wrapped__, self._self_instance,
>               args, kwargs)

c:\prg\reahl_env\lib\site-packages\wrapt\wrappers.py:523: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\prg\reahl_env\lib\site-packages\reahl\tofu\pytestsupport.py:152: in test_with_fixtures
    stack.enter_context(fixture)
c:\development\Lib\contextlib.py:426: in enter_context
    result = _cm_type.__enter__(cm)
c:\prg\reahl_env\lib\site-packages\reahl\dev\fixtures.py:55: in __enter__
    return super(ContextAwareFixture, self).__enter__()
c:\prg\reahl_env\lib\site-packages\reahl\tofu\fixture.py:320: in __enter__
    self.run_marked_methods(SetUp, order=reversed)
c:\prg\reahl_env\lib\site-packages\reahl\tofu\fixture.py:291: in run_marked_methods
    marked.method_for(self)()
c:\prg\reahl_env\lib\site-packages\reahl\dev\fixtures.py:127: in init_database
    self.system_control.initialise_database(yes=True)
c:\prg\reahl_env\lib\site-packages\reahl\component\dbutils.py:152: in initialise_database
    self.drop_database(yes=yes)
c:\prg\reahl_env\lib\site-packages\reahl\component\dbutils.py:185: in drop_database
    return self.db_control.drop_database(super_user_name=super_user_name, yes=yes)
c:\prg\reahl_env\lib\site-packages\reahl\postgresqlsupport.py:75: in drop_database
    Executable('dropdb').check_call(cmd_args + last_part)
c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py:71: in check_call
    return self.execute(subprocess.check_call, commandline_arguments, *args, **kwargs)
c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py:66: in execute
    return method([self.executable_file]+commandline_arguments, *args, **kwargs)
c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py:52: in executable_file
    return self.which(self.name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <reahl.component.shelltools.Executable object at 0x05568AD0>
program = 'dropdb'

    def which(self, program):
        #on windows os, some entrypoints installed in the virtualenv
        #need their full path(with extension) to be able to be used as a spawn command.
        #Python 3 now offers shutil.which() - see also http://stackoverflow.com/questions/377017/test-if-executable-exists-in-python
        executable = distutils.spawn.find_executable(program)
        if executable:
            return executable
>       raise ExecutableNotInstalledException(program)
E       reahl.component.shelltools.ExecutableNotInstalledException: Executable not found: dropdb

c:\prg\reahl_env\lib\site-packages\reahl\component\shelltools.py:61: ExecutableNotInstalledException
------------------------------ Captured log call ------------------------------
config.py                  198 WARNING  web.static_root in stage/2-sandbox\web.config.py is using a dangerous default setting: c:\appserv\water_poll
============================== warnings summary

**Comment by metaperl** [comment]
P.S. I've opened a thread which is only tangentially related to Reahl that you may want to contribute to - https://www.reddit.com/r/Python/comments/9tcrrz/how_would_you_go_about_understanding_a_large/

**Comment by IwanVosloo** [comment]
Mmm. On linux (Ubuntu) we control postgres via a number of commandline programs (see: [postgresqlsupport.py](https://github.com/reahl/reahl/blob/master/reahl-postgresqlsupport/reahl/postgresqlsupport.py))

These are: createuser, dropuser, [dropdb](https://www.postgresql.org/docs/current/static/app-dropdb.html), [createdb](https://www.postgresql.org/docs/current/static/app-createdb.html), pg_dump, pg_dumpall, pgrestore and psql.

Aren't these available on windows? 
Can you post their names/locations?
Are they in your path?

**Comment by metaperl** [comment]
>  On linux (Ubuntu) we control postgres via a number of commandline programs

Why not do this through SQLAlchemy? You can [issue drop database via SA](https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html#drop-database).

> Aren't these available on windows?
'
If I had installed Postgres locally, I'm sure they would be. However, I'm not controlling a local postgres database. I am using Postgres in the AWS cloud. I dont have personal console access to it.

Anyway, this is not a showstopper. But I do see something: dropping the database makes sense before running at test suite because you want pristine clean state. However, for my purpose of just adding demo data, I dont particulary want to drop my database.

I think instead of me hijacking the test functionality to add sample data, I should be writing standalone scripts. But I am not sure how to obtain a sqlalchemy connection in a script for a database configured in `reahl.config.py`.

**Comment by IwanVosloo** [comment]
> Why not do this through SQLAlchemy?

You might want to use a different ORM mapping tool, but also use PostgreSQL. So postgresqlsupport cannot be dependent on sqllchemysupport.

> But I am not sure how to obtain a sqlalchemy connection in a script for a database configured in reahl.config.py.

Yes, that can be done at various levels of trickyness.... An example that is maybe most familiar if you know SqlAlchemy is the `tutorial.test_model2` example. It is not explained in the newer tutorial anymore, but should be self-explanatory if you look at its code.

If you want to be fancier, you can build a `reahl xxxx` command and use our usual infrastructure from there. This stuff is seen as internal, and not documented.... but an example is the [MigrateDB command](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-commands/reahl/commands/prodshell.py#L263), which you can change into something like:

```
class MyCommand(ProductionCommand):
    """A description for MyCommand which is listed when you ask for help."""
    keyword = 'mycommand'
    def execute(self, args):
        super(MyCommand, self).execute(args)
        self.context.install()
        with self.sys_control.auto_connected():
              Session.save(MyPersistedObject(...))
              self.sys_control.commit()
```

The `self.sys_control` attribute is a [SystemControl](https://www.reahl.org/docs/4.0/component/dbutils.d.html#systemcontrol)

See also how you 'register' a new command with your project [as is done for MigrateDB](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-commands/.reahlproject#L37) your .reahlproject.

**Comment by IwanVosloo** [comment]
I am leaving this here still as a TODO so we can figure out why those scripts are not found on Windows - they should work, but we don't develop on Windows so we may have incorrect assumptions.

**Comment by metaperl** [comment]
> example that is maybe most familiar if you know SqlAlchemy is the tutorial.test_model2 example.

I think this is the way to go - quit trying to hijack test functionality for populating the database with data for integration testing. I plan to modify this script so that it accepts a path to the relevant config files... this is trivial to do.

That being said, I find it unusual that there is no way to run tests and specify the directory of configuration files they should run against as reported in https://github.com/reahl/reahl/issues/193

**Comment by IwanVosloo** [comment]
Cool, lets keep the other issues in the other issues.... 

... and just to keep track: 

> I am leaving this here still as a TODO so we can figure out why those scripts are not found on Windows - they should work, but we don't develop on Windows so we may have incorrect assumptions.

**Comment by craig-reahl** [comment]
Looking at the [ post install postgresql docs](https://www.postgresql.org/docs/11/install-post.html), it seems to be a setup issue and not a [reahl](www.reahl.org) bug per se. Perhaps we can add an _enhancement_ that lets the  users know that **dropdb** etc, are PostgreSQL commands that the reahl command wrapper was intending to execute. This would perhaps steer them in the right direction of adding the required path entries to their **PATH**

> If you installed into /usr/local/pgsql or some other location that is not searched for programs by default, you should add /usr/local/pgsql/bin (or whatever you set --bindir to in Step 1) into your PATH. Strictly speaking, this is not necessary, but it will make the use of PostgreSQL much more convenient.

I installed PostgreSQL 11.1 on  a windows 10 machine using the graphical installer [provided](https://www.postgresql.org/download/windows/) which is what I think most users would do. I can confirm that no PostgreSQL related paths were added to any environment variables.

_PS: Sysadmin type installations will most probably be done using [binaries](https://www.enterprisedb.com/download-postgresql-binaries) only, and setting up Environment variables would surely be for their own account._

**Comment by IwanVosloo** [comment]
Ok thanks. What you are saying is this is an example of #162 .

We can wrap these exceptions and raise a DomainException instead.

**Comment by metaperl** [comment]
> I installed PostgreSQL 11.1 on a windows 10 machine using the graphical installer provided which is what I think most users would do

No cloud user of Postgres has any need for installing Postgresql locally whatsoever. 

You have an unavoidable dependency on SQLAlchemy for the `reahl createdbtables` command that is never going away. I suggest the rest of the commands also use SQLAlchemy.

> This would perhaps steer them in the right direction of adding the required path entries to their PATH

What is simpler:

```
pip install reahl[sqlite,postgres]
reahl setup -- develop -N
reahl createdbuser
reahl createdb
reahl createdbtables
```

or ...

**all** of the above **AND** installing Postgres **AND** trying to get the paths so Reahl can find them **and** providing the database connection information in 2 places (`reahl.config.py` for Reahl and a `pg.conf` file or whatever for that database tool) so that a binary can do what could've already been done with SQLAlchemy without all of this extra work?

> Perhaps we can add an enhancement that lets the users know that dropdb etc, are PostgreSQL commands that the reahl command wrapper was intending to execute. 

And then you need to polymorphically come up with the same commands for every new database because you didnt let SQLAlchemy handle it for you? Just **adopt the policy that all reahl core database operations use SQLAlchemy.** 

This means 1 requirement regardless of how many databases a person needs to access. Instead of this same 1 requirement and all the headaches associated with getting binaries setup and the headaches of you writing documentation for it all... the current tutorial docs are fine if you implement those commands with SQLAlchemy. Otherwise, you have added a tremendous amount of unnecessary responsibility and dependencies.

**Comment by IwanVosloo** [comment]
I understand the issue reported here to be that on a windows install, the command you executed yielded the given stacktrace. My questions about the context went unanswered:

>Aren't these available on windows?
>Can you post their names/locations?
>Are they in your path?

The best we can do is assume from the stack trace that this is running on a windows box. We know we expect at least a **postgres client** to be installed in this context. Our efforts to replicate "a windows environment with postgres installed" showed that the needed client programs are installed, but that they may not be referenced in the user's PATH.  In this scenario it is sensible to report that error better, because better reporting would have helped a user to fix what was missing in their environment to make this work. 

That is a concrete solution to the reported concrete problem. Unless I misunderstood something in all of the above?

From [stackoverflow](https://stackoverflow.com/questions/33854798/how-do-i-install-just-the-client-tools-for-postgresql-on-windows) I understand that not **all** postgresql windows installers necessarily give you the option to install only the client programs, and that installing postgres in windows using the installers is not even necessarily working so well. If this is an issue, please log it as such with the postgresql project.

If the context of this issue is NOT a normal windows machine under your control, but an actual cloud-hosted windows, please give us more information so we can understand the context better.

**Comment by metaperl** [comment]
> My questions about the context went unanswered

I'm sorry I overlooked them. I also feel like my question has not been answered. I would appreciate it and here it is:

## Given:
1.  Reahl is an opinionated framework.
1. SQLAlchemy is a **must** for the internals of Reahl to operate.
1. Every other opinionated Python web framework has no requirements for database client binaries.
## Why:
Why would you want to require them when they only add more work and configuration nightmares? 

## Look at the facts:

* Nagare, the other python-only framework, [has a dropdb command](http://www.nagare.org/doc/nagare-admin.html) but it does not require you to have external binaries installed.
* Web2Py's [database abstraction layer](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer) has no requirement for external binaries, yet it drops and creates databases with ease.
* Django also has no need for external binaries.

You are creating more hurdles for people to jump through by requiring external binaries. I'm not sure why you can't see this?

> Aren't these available on windows?

Who cares? SQLAlchemy can already do it. `pip install SQLAlchemy` is a lot more portable than downloading binaries for the postgresql client.

> Can you post their names/locations?

I don't have any part of Postgresql installed locally. I use a Postgresql database out in the cloud. When I want to browse tables, I use db visualizer.

> Are they in your path?

No, because I have not installed it.

**Comment by metaperl** [comment]
A SQLAlchemy implementation of `dropdb` is available:
https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html#drop-database

It works great. I just used it.

**Comment by IwanVosloo** [comment]
> I also feel like my question has not been answered.

Ok, let me give you a fuller answer (and, thanks for your edit in the above reply - it really makes a difference).

The main issue here is that [SQLALchemy is actually not a must for Reahl](https://www.reahl.org/docs/4.0/devmanual/dependencyinjection.d.html).

As explained in the above link, it has a few classes that are implemented in terms of SQLAlchemy, and these are in their own component. So, it is quite easy to implement them using something else -- also in a separate component -- and install that instead. Then the framework and presumably your code will be done entirely in terms of this other, different persistence technology.

Sure, we don't have such an implementation currently because we thought it good enough to allow for such an implementation to be swapped in when needed. 

The idea is also to think further than only ORMs. Perhaps we (or someone) want to build a mongodb implementation instead!

To actually do this, one would have to also worry about a few other aspects, such as managing the database or dealing with migrations etc. So I am sure there will be problems to iron out if that happens.

[The design of the SystemControl ](https://www.reahl.org/docs/4.0/component/dbutils.d.html) is a corollary to the above. We needed to come up with a design that allows us to change database implementation and ORM implementation independently from one another.

We can't just throw all of that out the window...

Now, your issue reported here is a bit difficult for me to define because it starts off with a stacktrace, then goes into a need you have for creating data in a staging environment on (I assume) AWS. And it seems you got your answer for dealing with creating the data you needed. I also understood that you referred to having to install postgresql libraries when you said:

> Anyway, this is not a showstopper.

Either way. If there is a need here I'd like to understand the need first before I want to start debating a specific solution to it. If I understand the need, I can possibly come up with a number of competing solutions and debate them all based on not only individual merit, or what others have done, but also in terms of all the constraints we try to satisfy. (One of these being maintaining the flexibility to swap out the ORM for something else.)

We also have to use an understanding of the need to be able to prioritise, because as it happens we always have more things that need to be done than we can actually do...so we have to choose what is more pressing.

Examples of other solutions are:

1. If there is a need for being able to drive postgresql via SQLAlchemy, we can create a different component which you can install instead of postgresqlsupport which IS dependent on sqlalchemysupport, but which is optional.

2. If the context in which this error happens is on some cloud service, we can investigate that offering and we might find that they have the client libraries somewhere. With that knowledge we could trivially solve the issue be setting the PATH correctly in that environment.

3. If the real thing that makes this issue pressing is your need to create test data, then perhaps the proper solution is to write a custom script that does that.

Either way, given that your issue seems to be sorted, we thought we should take this logged issue and make at least one little thing better: how we report the error when the executable is not found.

If there is an important need for (1) above, then I'd actually prefer to create a new issue in which we state that the need and context is. 

Perhaps postgresql client programs ARE in fact installed on AWS, and CAN be found if the PATH is set correctly as per (2).

Your answers in the context of AWS would make it so much easier to support this environment because AWS is not one of the environments we work with.

**Comment by metaperl** [comment]
> Perhaps postgresql client programs ARE in fact installed on AWS, and CAN be found if the PATH is set correctly as per (2).

They might be, but I would need ssh access to the cloud server, which I do not have.

I use db visualizer locally. It allows me to connect to SQLite and Postgres databases. And even MSSQL and others. I have no desire to install postgres binaries and I dont have permissions for that. My windows machine came with db visualizer and there is no guarantee that I would be approved for installing them and I dont savor the idea of trying to tell my superiors why I need it, wasting their time for something with less functionality than db visualizer.

**Comment by IwanVosloo** [comment]
I do think we still need to do something here to deal with this scenario.... but I was wondering how you are coping currently? How do you get a database created, etc? Do you have to do it by hand using other tools?

**Comment by metaperl** [comment]
I wrote a SQLAlchemy script to drop and create my database:

```python
"""Database Processing Script

This script:

a - can drop a database
b - can build a database
c - can call plugins, mainly for the purpose of inserting data into database.

Usage:

# Drop the dev database
python dbloader.py --drop-db DEV

# Create and seed the dev database
python dbloader.py --build DEV

# Run the sample plugin
python dbloader.py --plugin=sample DEV

Staging Environments:

Look in appconfig.py to see them:
--------------------------------
* LOCAL
* DEV
* STAGING
* QA
* PROD
"""

import logging
import random
import uuid
from datetime import datetime, timedelta

from plumbum import cli, local
from reahl.component.config import StoredConfiguration
from reahl.component.context import ExecutionContext
from reahl.domain.systemaccountmodel import EmailAndPasswordSystemAccount
from reahl.sqlalchemysupport import Session, metadata


import datatablebootstrap
from appconfig import App
from datatablebootstrap import Ability, Check, UserAbility

APP = App()
LOGGER = logging.getLogger(__name__)

ability_labels = 'Inactive SearchChecks EditChecks CreateUser'.split()


def new_account(email='admin@site.org'):
    password = 'topsecret'
    account = EmailAndPasswordSystemAccount(email=email)
    Session.add(account)
    account.set_new_password(account.email, password)
    account.activate()
    return account


def new_check(bank_account_id, checkno):
    day = random.randint(1, 25)
    month = 11
    year = 2018
    issue_date = datetime(year, month, day)
    cleared_date = issue_date + timedelta(days=random.randint(5, 20))
    tid = str(random.randint(1545, 678678))

    def random_check_amount():
        return random.randint(5000, 200000)

    if random.randint(0, 100) < 50:
        amount = amount_cleared = random_check_amount()
    else:
        amount = random_check_amount()
        amount_cleared = random_check_amount()

    _ = Check(bank_account_id=bank_account_id, check_number=checkno,
              amount=amount, amount_cleared=amount_cleared,
              date_issued=issue_date, date_cleared=cleared_date,
              transaction_id=tid, status_id=random.randint(0, 9),
              issue_type_id=random.randint(0, 1),
              )
    Session.add(_)
    return _


def dummy_data():
    ability = dict()
    for _ in ability_labels:
        ability[_] = datatablebootstrap.Ability(label=_)

    LOGGER.warning(f"Ability dict={ability}")

    account_ability = dict()

    # inactive
    # viewer
    # editor
    # security
    # admin

    account_ability['admin'] = 'EditChecks CreateUser'.split()
    account_ability['security'] = ['CreateUser']
    account_ability['editor'] = ['EditChecks']
    account_ability['viewer'] = ['SearchChecks']
    account_ability['inactive'] = ['Inactive']

    for account, abilities in account_ability.items():
        acct = new_account(email=f"{account}@ofiglobal.com")
        for ability in abilities:
            _ability = Session.query(Ability).filter_by(label=ability).one()
            Session.add(UserAbility(account_id=acct.id, ability_id=_ability.id))

    import random

    for i in range(0, 10):
        bank_account = random_table_row(datatablebootstrap.BankAccount)
        check_number = str(random.randrange(12345, 678910))
        new_check(bank_account.id, check_number)


def random_table_row(t):
    import random
    rand = random.randrange(0, Session.query(t).count())
    row = Session.query(t)[rand]
    return row

def id_label_table_to_dict(t):
    _ = dict()

    for row in Session.query(t).all():
        _[row.label] = row.id

    return _


def populate(table, values):
    for i, value in enumerate(values.splitlines()):
        value = value.strip()
        Session.add(table(id=i, label=value))

    Session.commit()


def populate_check_issue_types():
    data = """System-Generated
Manual
Paid
"""

    populate(datatablebootstrap.CheckIssueType, data)


def populate_plan_types():
    data = """PC529
NM529
"""

    populate(datatablebootstrap.CheckPlan, data)

def populate_bank_accounts():
    data = """PC529
NM529
"""
    plan_id = id_label_table_to_dict(datatablebootstrap.CheckPlan)
    data = ""xtz
"""

    for i, line in enumerate(data.splitlines()):
        LOGGER.warning(f"Processing {line}")
        plan_label, account_number, account_type = line.split()
        plan_label += '529'
        account_number = int(account_number)
        Session.add(datatablebootstrap.BankAccount(
            plan_id=plan_id[plan_label],
            account_number=account_number,
            account_type=account_type))

    Session.commit()

def populate_check_statuses():
    data = """xyz
"""

    populate(datatablebootstrap.CheckStatus, data)


def populate_abilities():
    description = {
        'Inactive': "not enabled for any actions.",
        'SearchChecks': "are able to search for and view checks.",
        'EditChecks': "are able to search for and edit checks.",
        'CreateUser': "are able to create new users and set permission levels."
    }
    for ability in ability_labels:
        Session.add(datatablebootstrap.Ability(label=ability, description=description[ability]))


class MyApp(cli.Application):
    # PROGNAME = "db-setup"
    VERSION = "7.3"

    plugin = cli.SwitchAttr(
        "--plugin", str, default=None,
        help="load a plugin file from db/plugin/ to execute against a built database. Ex: python dbloader.py --plugin=sample"
    )
    build = cli.Flag('build', help='Create the database and populate with seed data.')
    drop_db = cli.Flag('drop-db', help="Drop the database. BE CAREFUL!")
    create_db = cli.Flag('create-db', help="Create the database.")
    create_tables = cli.Flag('create-tables', help="Create the database tables.")
    build_lookups = cli.Flag('build-lookups', help="Populate the lookup tables.")
    dummy_data = cli.Flag('dummy-data', help="Add dummy data.")

    def _drop_db(self):
        from sqlalchemy_utils.functions import drop_database
        drop_database(self.db_uri)

    def _create_db(self):
        from sqlalchemy_utils.functions import create_database
        create_database(self.db_uri)

    def _create_tables(self):
        reahl = local["reahl"]
        reahl["createdbtables", APP.stage.path]()

    def _build_lookups(self):
        LOGGER.warning("Building lookups.")
        populate_check_issue_types()
        populate_check_statuses()
        populate_abilities()
        populate_plan_types()
        populate_bank_accounts()

    def main(self, stage_str):
        # Boilerplate to get SQLAlchemy URL and Reahl convenience to SQLAlchemy

        APP.set_stage(stage_str)
        print("I will now read {0}".format(APP.stage))
        ExecutionContext().install()
        config = StoredConfiguration(APP.stage.path)
        config.configure()

        self.db_uri = config.reahlsystem.connection_uri
        print("DB URI = {}".format(self.db_uri))

        metadata.bind = self.db_uri

        # End Boilerplate

        APP.protect_production()

        if self.drop_db:
            self._drop_db()

        if self.create_db or self.build:
            self._create_db()

        if self.create_tables or self.build:
            self._create_tables()

        if self.build_lookups or self.build:
            self._build_lookups()
            Session.commit()
            #LOGGER.warning("Inspect database and then hit return.")
            #input("Inspect database and then hit return.")

        if self.dummy_data or self.build:
            dummy_data()

        if self.plugin:
            import importlib
            module = importlib.import_module(f"db.plugin.{self.plugin}", '.')
            plugin = module.Plugin(APP)
            return_code = plugin.run()
            if not return_code:
                Session.commit()
                return 0
            else:
                LOGGER.warning(f"Plugin {self.plugin} failed with code {return_code}.")
                return return_code

        Session.commit()


if __name__ == "__main__":
    MyApp.run()

```

**Comment by IwanVosloo** [comment]
This issue is closed, but I've revived its underlying need in #276
