### ISSUE TITLE
Code sample does not Use AccountManagementInterface to find the current LoginSession.

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#184]
In the [Re-use: Allowing users to log in to your system](https://www.reahl.org/docs/4.0/tutorial/loggingin.d.html) we read 

> Use AccountManagementInterface in your code to find the current LoginSession.

However on [line 216](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/accessbootstrap/accessbootstrap.py#L215) we see that the current LoginSession is not accessed via an attribute of AccountManagementInterface - it is accessed separately.

**Comment by IwanVosloo** [comment]
Thanks. need to fix the tutorial docs.
