### ISSUE TITLE
Dynamically naming buttons

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#185]
I was exploring the possibility of having a logout button with the label "Logout $username" and I discovered that [the logout button gets its label from its associated event](https://github.com/reahl/reahl/blob/master/reahl-domain/reahl/domain/systemaccountmodel.py#L323)

I'm not aware of any GUI toolkit that has ever done this. 

I thought dynamically labelling the button would be a simple task of supplying an argument [at button creation time](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/accessbootstrap/accessbootstrap.py#L204) using this one tutorial app as an example.

**Comment by IwanVosloo** [comment]
That's correct, all Inputs derive things like labels from their Fields/Events.

So the point is you want to use the Event that's there, but with different metadata.  This SHOULD be possible but we did not think of this specific requirement before.

We do something something similar with things like [Field.as_required](https://www.reahl.org/docs/4.0/component/modelinterface.d.html#reahl.component.modelinterface.Field.as_required) and [Field.with_validation_constraint](reahl.component.modelinterface.Field.with_validation_constraint).

These methods make a copy of the Field and then change something on the copy.

We'll need to build something similar for this scenario.

In the mean time, you can do what we did in the implementation of the methods mentioned above, something like:

```
custom_logout = account_management.events.logout_event.copy()
custom_logout.label = 'Log out %s' % user.email_address
self.add_child(Button(self, custom_logout))

```

We can in future turn that into:

`account_management.events.logout_event.with_label('Log out %s' % user.email_address)`

That said, its is a very tricky thing to provide vocabulary on a high level of abstraction. We have to experiment... Perhaps in the case of Buttons one should run the risk of being inconsistent and rather provide a kwarg that overrides the label from the Event, so you can say:

`Button(self, account_management.events.logout_event, label='xxxx')`

Right now, I'd want to be conservative and stick to the consistent way, which is to provide a `.with_label` method.
