### ISSUE TITLE
"next" from Hello World does not go to the next section of the tutorial

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#187]
From [the tutorial](https://www.reahl.org/docs/4.0/tutorial/index.d.html) if you click on [Hello world](https://www.reahl.org/docs/4.0/tutorial/gettingstarted-develop.d.html) and then scroll to the bottom of the page and click next you get a [what's changed](https://www.reahl.org/docs/4.0/whatchanged.d.html) document instead of the next section of the tutorial.

**Comment by IwanVosloo** [comment]
Ok, thanks. Will have to investigate --- something must be amiss with its TOC.

**Comment by craig-reahl** [comment]
gettingstarted-develop.rst is included in more than one TOC. It seem Sphinx picks up the first/last TOC it is defined in and then generates the **previous** and **next** URLS based on that. 
The two pages including it, and perhaps why there is an expectation what **next** should be:

> ...
> Get started
> 
>     Install Reahl
>     Hello World!
>     Run more examples
> ...

and here:

> ...
> Contents:
> 
>     Documentation overview
>     Hello World!
>     What changed in version 4.0
> ...

**Comment by IwanVosloo** [comment]
Ok, thanks.... MMM.  The only fix I see for that is to remove it from the last one (doc/index.rst)...
