### ISSUE TITLE
Relating SystemAccounts to roles

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#188]
Hello, if one wanted to assign roles to users of a web app, how would one do so? I've looked at the [Party model](https://github.com/reahl/reahl/blob/master/reahl-domain/reahl/domain/partymodel.py) and it does not have a label field.

The way I envision things working is a new user registered via  EmailAndPassWordAccount is assigned a default role of `viewer`. Only via a SQL update will the role of any user be changed to `editor`.

I could certainly create a `Role` SQLAlchemy class for this purpose, but was wondering if I had overlooked something.

**Comment by IwanVosloo** [comment]
Roles can be complicated, hence we opted to NOT make decisions about this sort of thing on behalf of users of the framework.

That said, you get simple roles and more complicated roles. Simple roles are just labels attached to a Person. More complicated roles pertain to some other entity, such as being the Owner of a particular InvestmentPortfolio vs being the Broker for a set of such portfolios, etc. Even more complicated roles can keep track of the timeframe for which they are valid. Or the specific rights someone with that role has, as pertaining to the object in question.

An example of this is done in [tutorial.accessbootstrap](https://www.reahl.org/docs/4.0/tutorial/accesscontrol.d.html). In this example a Collaborator "role" serves to link an EmailAndPasswordSystemAccount to an Addressbook, and on it, it keeps track of more detailed information ("rights") in the context of that role:

```
class Collaborator(Base):
    __tablename__ = 'access_collaborator'
    id      = Column(Integer, primary_key=True)

    address_book_id = Column(Integer, ForeignKey(AddressBook.id))

    account_id = Column(Integer, ForeignKey(EmailAndPasswordSystemAccount.id), nullable=False)
    account = relationship(EmailAndPasswordSystemAccount)

    can_add_addresses = Column(Boolean, default=False)
    can_edit_addresses = Column(Boolean, default=False)

```

Typically such a role should be from, say a Party of some sort (I can't remember why we did not use the Party in that example...)

The idea behind Party as it is now, is that you can inherit from it to create a Person containing whatever details you need (or also a Company, for example). We did not want to venture that far with the model ourselves.

The whole topic of parties and roles is actually surprisingly complex and requirements vary between projects. I suggest [Martin Fowler's thoughts](https://www.martinfowler.com/apsupp/roles.pdf) on the topic if you're interested.

I don't know enough of your domain... but it seems viewer / editor would also be viewer/editor *of something*.  Perhaps something like our Collaborator example can work? 

Or perhaps you can have a simpler world, and just have Role class, that points back to Party using a foreign key relationship to yield a one-to-many relationship between Party and Role. Your Role class can then have a label attribute with some text?

You can also inherit a Person class from Party and put whatever you want in there.

It all depends on how much complexity your domain really needs...

**Comment by metaperl** [comment]
I have something simple that is workable for me:

```python

# m-to-n association table between EmailAndPasswordSystemAccount and Ability
account_ability = Table('account_ability', Base.metadata,
        Column('account_id', ForeignKey('emailandpasswordsystemaccount.id'), primary_key=True),
        Column('ability_id', ForeignKey('ability.id'), primary_key=True)
)


class Ability(Base):
    __tablename__ = 'ability'

    id = Column(Integer, primary_key=True)
    name = Column(UnicodeText, nullable=False, unique=True)

    accounts = relationship("EmailAndPasswordSystemAccount",
                secondary=account_ability,
                backref="abilities")

    @classmethod
    def edit_for(cls, account):
        return 'edit' in [ability.name for ability in account.abilities]

```
