### ISSUE TITLE
Formatting a key and value so that the keys all line up in terms of width.

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#189]
In all the tutorial examples, when Reahl formats two things on the same line (such as [the email address and  comment](https://www.reahl.org/persistence) it does so via a string concatenation of the two values. However, it is much more common for two things on the same line to have the first thing take up a fixed width that is constant for all first elements, regardless of their actual length as you can see here:

![label and field](https://user-images.githubusercontent.com/21293/47935619-a2aa3f00-dea0-11e8-9642-a03a9e3fe7de.png)

How does one achieve such formatting in Reahl?

**Comment by IwanVosloo** [comment]
You can use a  [GridFormLayout](https://www.reahl.org/docs/4.0/web/bootstrap/forms.d.html#gridformlayout)

**Comment by metaperl** [comment]
Yes, I was able to find an example of using `GridFormLayout` in [the test code](https://github.com/reahl/reahl/blob/master/reahl-web/reahl/web_dev/bootstrap/test_form.py#L56) and I replaced the FormLayout in [an example](https://github.com/reahl/reahl/blob/master/reahl-doc/reahl/doc/examples/tutorial/addressbook2/addressbook2.py#L32) and got it to work. Thanks.

**Comment by IwanVosloo** [comment]
Cool. Leaving this issue here anyway, so we can add something about this to the docs.

**Comment by IwanVosloo** [comment]
Done in pull request #199
