### ISSUE TITLE
Parameterised view tutorial issues

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#190]
In the [parameterized tutorial](https://www.reahl.org/docs/4.0/tutorial/parameterised.d.html) we read the following in [the programmatic arguments section](https://www.reahl.org/docs/4.0/tutorial/parameterised.d.html#programmatic-arguments):

> Not all the arguments passed to the .assemble() method of a View need to be parsed from the URL of the View.

My comment on this is: the View class does not have an assemble method. The subclasses of View, such as `UrlBoundView`, do. 

This section continues:

> Sometimes it is useful to pass an object that is available in the .assemble() of the containing UserInterface to the .assemble() of one of its Views .

My comment on this is: OK, well where is the example doing this?

Next we read:

> In cases where there are multiple Transitions possible, things get tricky:

My comment is: this is the second time that multiple run-time-computed transitions are discussed, the first being [at the end of the connecting views tutorial](https://www.reahl.org/docs/4.0/tutorial/connectingviews.d.html#guards). However, in neither case does the tutorial link to source code exemplifying these even though [such source code does exist](https://www.reahl.org/pageflow/).

Now, having seen the use of a single guard to control page transition, it is possible to transition based on a compound of two predicates, e.g:

1. if `search_returns_a_row()` AND `current_user_has_ability('edit')` then transition from search_page to edit_detail_page.
1. if `search_returns_a_row()` AND `current_user_has_ability('view')` then transition from search_page to view_detail_page.
1. transition from search_page to no_results_page

In my actual application, a single page is re-used for edit and view, so a single guard will suffice. But I'm sure inquiring minds want to know about compound predicates. If nothing else, you could create your compound test and then supply that compound test as a single method to `Action`.

**Comment by IwanVosloo** [comment]
Ok, thanks, we'll have to polish those docs/examples a bit.

There's also a test that shows passing of arguments to an UrlBoundView, see [ParameterisedView](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-web/reahl/web_dev/appstructure/test_parameterised.py#L32) in [reahl-web/reahl/web_dev/appstructure/test_parameterised.py](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-web/reahl/web_dev/appstructure/test_parameterised.py) and how it is used in [test_views_with_parameters](https://github.com/reahl/reahl/blob/2be7bfbbc9848ade9751883e12d23ba10612d697/reahl-web/reahl/web_dev/appstructure/test_parameterised.py#L88)

(I'll come back a bit later to respond on your last "compound predicate" question.)

**Comment by IwanVosloo** [comment]
On the "compound predicate" issue: the idea is that you can just create a function that uses normal Python to do what you want, and supply that function as the Guard's Action.

There is, however an inverse - action called [Not](https://www.reahl.org/docs/4.0/component/modelinterface.d.html?highlight=#reahl.component.modelinterface.Not) which allows you to have two guards one of which is the inverse of the other. So then you can have something like:
`a = Action(current_user_has_ability('view'))` on one and 
`b = Not(a)` on the other

**Comment by IwanVosloo** [comment]
BTW, I just spotted an issue with:

> `Action(current_user_has_ability('view'))`

Action takes a callable, to it would have to be something like:

```
Action(functools.partial(current_user_has_ability, 'view'))
```
