### ISSUE TITLE
adding @session_scoped to a table does not migrate the related schema

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#204]
I added `@session_scoped` to a class and then got the error:

    psycopg2.ProgrammingError: column checkrecon_search.user_session_id does not exist

It was an easy fix to add the column. This is more of an FYI than anything.

**Comment by IwanVosloo** [comment]
Whatever you add do your model will require you to write a migration for that change and also Up the version of your project. We cannot automatically migrate something if you make a code change that results in a new schema being needed. Adding @session_scoped definitely changes the underlying schema.
