### ISSUE TITLE
NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#230]
I successfully upgraded to ` reahl-component-4.0.4` and in production I am getting this error:

    NameError: name 'warnings' is not defined

And [the warnings package is accessed](https://github.com/reahl/reahl/blob/master/reahl-component/reahl/component/config.py#L295) but not imported.

**Comment by metaperl** [comment]
The version of reahl-component on [PyPi](https://pypi.org/search/?q=reahl) is still the one with this bug. This is a showstopper for me to upgrade. When will we see 4.0.5 released to PyPI?

**Comment by IwanVosloo** [comment]
That is a nasty one... We'll try to make a plan as soon as possible.

**Comment by IwanVosloo** [comment]
4.0.5 is now available
