### ISSUE TITLE
Returning HTTP status 200 for a GET request to /health

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#239]
By default, Amazon AWS pings your site on the URL `/health` and expects a HTTP status 200 returned as part of it's [health check protocol](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html). 

A [sample Django app](https://tech.octopus.energy/news/2016/05/05/django-elb-health-checks.html) does return HTTP status 200 [per the docs](https://docs.djangoproject.com/en/2.1/ref/request-response/#id3). 

I have created a Reahl view for the expected path:

```python
        health = self.define_view('/health', title='Health Check')
        health.set_slot('main', LegalNotice.factory('Health check passed.', 'health'))
```
 but I don't believe Reahl returns status 200 with web pages does it? How can I return status 200 for this view.

**Comment by IwanVosloo** [comment]
Sure, Reahl does return status code 200 for a successful GET request. [That is what the HTTP spec requires](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.1). If you hit your URL above using a web browser and see a normal page, you can assume it returned a 200.

**Comment by metaperl** [comment]
The problem is that the health check must serve over https.

As long as my app makes no setting changes to the default settings in `web.config.py`:

```python


from __future__ import print_function, unicode_literals, absolute_import, division
from datatablebootstrap import MyUI

web.site_root = MyUI

# make no changes to defaults
# web.default_http_port = 80
# web.default_http_port = 8363
# web.encrypted_http_port = 8363
# web.default_http_scheme = 'https'
# web.default_http_port = 443
# web.encrypted_http_scheme = 'https'
# web.encrypted_http_port = 443

```

Then you can make an https request to the health URL succesfully:

```
H:\>curl -vk https://localhost:8363/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8363 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost
*  start date: Mar  4 09:05:22 2014 GMT
*  expire date: Feb 27 09:05:22 2034 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /health HTTP/1.1
> Host: localhost:8363
> User-Agent: curl/7.63.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
```

but forcing everything in a Reahl app to https is problematic for even simple examples: https://github.com/reahl/reahl/issues/240

**Comment by craig-reahl** [comment]
> The problem is that the health check must serve over https.

Hi, I see that your widget name is LegalNotice. You could set this in its **__init__** method:

`self.set_as_security_sensitive()`

Setting this on a widget would force the pages in appears in to be served over **https**

**Comment by craig-reahl** [comment]
...unless you just run your app/site completely [under https](https://github.com/reahl/reahl/issues/164#issuecomment-433697945) off course

**Comment by IwanVosloo** [comment]
I am confused. You talk about AWS here, but you have an example above that looks like it runs on your local machine. Those two scenarios are completely different.

I can tell you how to configure the app to https only on aws if you can tell me on which port aws serves https.

> but forcing everything in a Reahl app to https is problematic for even simple examples: #240

I don't understand why its problematic. Can you explain?

**Comment by metaperl** [comment]
> I don't understand why its problematic. Can you explain?

I'm starting to think that the problems with https on AWS have to do with the fact that there is a good amount of non-trivial configuring that needs to be done for https to work.

At any rate: pure http works fine on AWS with this config:
```python
from datatablebootstrap import MyUI

web.site_root = MyUI

web.default_http_port = 80
web.default_http_scheme = 'http'

web.encrypted_http_port = 80
web.encrypted_http_scheme = 'http'
```

But 3 attempts at getting HTTPS to work all fail:
1. https://github.com/metaperl/reahl/wiki/Trivial
1. https://github.com/metaperl/reahl/wiki/AWS-Common-Sense
1. https://github.com/metaperl/reahl/wiki/AWS-Like-Local - in this attempt I force everything to https just as I did on localhost. But it failed with redirect loops.

I think the wise thing to do is to reach out to one of our AWS admins with the following request:
```
I have my Reahl app working locally, serving everything over https. 
I want to configure my app for AWS over https but:
1.I do not know what port Apache listens on for https (I guess 443)
2.I do not know where to see how apache is configured on AWS - 
   the default setup is creating redirect loops
```

**Comment by IwanVosloo** [comment]
Yes, I know AWS config is usually not trivial. While you wait for their response, can I ask you to supply some more info?

I see from [AWS docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https.html) that there are 3 ways to set up HTTPS on EB:
- [configure https+a certificate on a load balancer, which then forwards via plain HTTP to your EC instance](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-elb.html); or
- [not use a load balancer, and configuring your EC instance to serve HTTPS](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance.html); or
- [a combination of the two](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-endtoend.html); or
- [let the load balancer pass tcp connections to an HTTPS server on the EC instance](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-tcp-passthrough.html).

Which option of the above you choose to use on AWS may influence how you'd set up Reahl.

Do you know which option you are aiming for?
