### ISSUE TITLE
Link to Dealing with user input is broken

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#242]
From the home page, if you click on ["Dealing with user input"](https://www.reahl.org/validation) and enter an email address, you get a broken link.

**Comment by IwanVosloo** [comment]
Yes, that can happen if you actually press the enter button after entering a valid email. We did not really want to pollute the example with more stuff than only the validation and never intended for someone to hit enter.  I guess we can add a call to `.define_event_handler()` to prevent it from breaking
