### ISSUE TITLE
Up arrow / down arrow on Datatable does not render correctly

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#243]
I [created a `DataTable`](https://gist.github.com/metaperl/03080de98b1dcb01216321e4c049e60d#gistcomment-2791110) but when a column is sorted, the up arrow/down arrow is not rendered correctly:

![capture2](https://user-images.githubusercontent.com/21293/50306982-4309f200-0454-11e9-942b-0d4379bbe036.PNG)

**Comment by IwanVosloo** [comment]
That character is a UTF-8 character. I'd want to investigate several things:
- does your webserver serve pages as UTF-8?
- does your browser honour that?
etc.

Here is what I get  (and with firefox, you can right-click on the page and choose page info, which shows the charset to be utf-8 in my case as it should be):
![screenshot from 2018-12-22 10-40-14](https://user-images.githubusercontent.com/2255287/50372401-94da8580-05d6-11e9-9378-718a7fdb8e38.png)

You can also do right click, inspect element and then choose the network tab. Re-load that url and check what the response headers look like. There should be a Content-Type: text/html; charset=utf-8.

If you can check what these things are in your environment we can try figure out what is happening.

**Comment by metaperl** [comment]
One thing is for certain. The browser honors utf-8. Why? Because a `DataTable` at reahl.org's frontpage renders fine:

![image](https://user-images.githubusercontent.com/21293/50457114-70ecac00-0916-11e9-8ef5-e6c474b5090e.png)

**Comment by IwanVosloo** [comment]
What I am trying to determine is whether the correct headers are sent to your browser from your webserver.  Without the info I asked for from your end I have nothing to go on to try and solve your issue.

**Comment by metaperl** [comment]
The arrows render fine on AWS. The reported problem is an artifact of the local web server and does not deserve any time to fix.
