### ISSUE TITLE
Executing raw sql from a command-line tool using Reahl SQLAlchemy integration

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#244]
I have a command-line tool that allows me to handle various database
processes related to my Reahl web app. One such function in the tool
is the ability to write [small plugins which perform database actions](https://gist.github.com/metaperl/543723160791ed1119f96c946ee094e4#file-dbloader-py-L298).

This [sample plugin](https://gist.github.com/metaperl/543723160791ed1119f96c946ee094e4#gistcomment-2811536) runs just fine, leveraging methods from its base call.

However, after implementing a `raw_sql` method in [my base class](https://gist.github.com/metaperl/543723160791ed1119f96c946ee094e4#gistcomment-2811543), I tried to write [a plugin which executes raw_sql](https://gist.github.com/metaperl/543723160791ed1119f96c946ee094e4#gistcomment-2811542), similar to [the execute_one() method in Reahl](https://github.com/reahl/reahl/blob/master/reahl-sqlalchemysupport/reahl/sqlalchemysupport/sqlalchemysupport.py#L329), and it fails with this stacktrace:

```
(env-reahl) c:\appserv\check_recon>python dbloader.py --plugin check_view2 DEV
python dbloader.py --plugin check_view2 DEV
WARNING:reahl.component.config:web.static_root has been defaulted to a value not suitable for production use: "c:\appserv\check_recon". You can set it in stage/1-dev\web.config.py
I will now read Stage.DEV
DB URI = postgresql://crdevuser:crdevuser@sc-534482906438-pp-kikgo-ofiquickstartrdsdbcluste-qczqd8jbbwp.cluster-ciwyutzqpmca.us-east-1.rds.amazonaws.com/checkrecon
Traceback (most recent call last):
  File "dbloader.py", line 322, in <module>
    MyApp.run()
  File "c:\prg\env-reahl\lib\site-packages\plumbum\cli\application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "dbloader.py", line 310, in main
    return_code = plugin.run()
  File "c:\appserv\check_recon\db\plugin\check_view2.py", line 106, in run
    self.raw_sql(self.RAW_SQL)
  File "c:\appserv\check_recon\db\plugin\base.py", line 25, in raw_sql
    self.Session.execute(sql)
  File "c:\prg\env-reahl\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\prg\env-reahl\lib\site-packages\sqlalchemy\orm\session.py", line 1184, in execute
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "c:\prg\env-reahl\lib\site-packages\sqlalchemy\orm\session.py", line 1452, in get_bind
    ', '.join(context)))
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on SQL expression or this Session

(env-reahl) c:\appserv\check_recon>

```

**Comment by metaperl** [comment]
I think my description is a bit long-winded. My question can be simplified to

> the script below creates SQLAlchemy row instances and commits them to the database. How could one replace the call to `demo_setup()` with a call to `raw_sql()` such that the raw sql is executed and the view is created:

```python


import random
import sys

from sqlalchemy import Column, Integer, UnicodeText
from datatablebootstrap import Check, Ability, account_ability, MyUI
from reahl.domain.systemaccountmodel import EmailAndPasswordSystemAccount
from reahl.tofu.pytestsupport import with_fixtures
from reahl.sqlalchemysupport_dev.fixtures import SqlAlchemyFixture

from reahl.sqlalchemysupport import Session, Base, metadata
from reahl.component.context import ExecutionContext
from reahl.component.config import StoredConfiguration, ReahlSystemConfig


def br():
    print("===========================================")

def demo_setup():

    q = Session.query(Check).all()
    print(q)

    br()

    q = Session.query(Check).filter(Check.check_number == '9adfadfasdf').first()
    print(q)

    br()

    for account_label in 'admin editor viewer'.split():
        print("--- {}".format(account_label))
        account = Session.query(EmailAndPasswordSystemAccount).filter_by(email='{}@some.org'.format(account_label)).one()
        for ability in account.abilities:
            print("    {}".format(ability.name))

def raw_sql():
    return  """
CREATE VIEW
    checks_v2
    (
        plan_type,
        a_number,
        a_type,
        c_number,
        amount,
        amount_c,
        date_i,
        date_c,
        status,
        issue_type,
        transaction_id
    ) AS
SELECT
    *
FROM
    pawan_x
"""

def populate():
    ExecutionContext().install()


    config_dir = sys.argv[1]
    config = StoredConfiguration(config_dir)
    config.configure()

    db_uri = config.reahlsystem.connection_uri
    print("DB URI = {}".format(db_uri))

    metadata.bind = db_uri

    demo_setup()

    Session.commit()


if __name__ == '__main__':
    populate()
```

**Comment by metaperl** [comment]
I have a working solution. Not pretty, but it works. I just use [engine.connect()](https://docs.sqlalchemy.org/en/latest/core/connections.html?highlight=stored%20procedure) which I create below.

```python
    def connect(self, config):
        """Creates the SQLAlchemy Engine, bind it to the metadata and instrument the persisted classes
           for the current reahlsystem.root_egg."""
        # assert not self.connected
        context = ExecutionContext.get_context()

        # db_api_connection_creator = context.system_control.db_control.get_dbapi_connection_creator()

        create_args = {'pool_pre_ping': True}
        # if db_api_connection_creator:
        #     create_args['creator'] = db_api_connection_creator

        self.engine = create_engine(config.reahlsystem.connection_uri, **create_args)
        # self.engine.echo = self.echo
        connection = self.engine.connect()
        metadata.bind = self.engine
        Session.configure(bind=self.engine)

        return connection


```

**Comment by IwanVosloo** [comment]
Glad you got it working... I don't have enough context of your code here to really understand what caused that issue. Perhaps this info can help your understanding though:

The reahl.sqlalchemysupport.metadata and Base are set up to use a [sqlalchemy scoped session](https://docs.sqlalchemy.org/en/latest/orm/contextual.html). So if what you are doing further on with the database includes using such objects, you need to be aware of this fact.

The scope that this session is linked to, is the current reahl ExecutionContext. To have an ExecutionContext available in the scope of your database operations, you need to:
- create an ExecutionContext; 
- install it in the scope of some function; and then
- call the code that will do database operations from this function.

An example of this is in the `test_model` function of the `tutorial.test_model2` example.

How this works is: the ExecutionContext is associated with all code in the function where it is installed and everything in the call stack below it. When your code wants to find a sqlalchemy session, it will first look for the current ExecutionContext, and then obtain the sqlalchemy session associated with that ExecutionContext.

PS: so if your code does NOT use reahl.sqlalchemysupport.Session (and metadata and Base) then you can ignore all of the above and just follow sqlalchemy docs.
