### ISSUE TITLE
delaying connection creation yields "sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper Mapper|UserSession|usersession or this Session"

### ISSUE THREAD

**Issue by metaperl** [reahl/reahl#246]
In an attempt to work around the connection pool overflow issues reported in https://github.com/reahl/reahl/issues/232 I attempted to create call `ReahlWSGIApplication.start()` with `connect=False` in order to delay connections until needed:

```python
class MyApp(ReahlWSGIApplication):
    ...

application = MyApp.from_directory(app_dir)

def main():
    # print(APP.status)
    application.start(connect=False)

main()
```

However this leads to a new error: **sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper Mapper|UserSession|usersession or this Session"**

**Comment by metaperl** [comment]
This is low priority.

**Comment by IwanVosloo** [comment]
Yes... connecting for us means a number of things, including keeping sqlalchemy happy. You can't NOT connect and expect things to work. Lets rather help you getting #232 dealt with (I answered there)
