### ISSUE TITLE
Update slimit and cssmin

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#336]
Both these projects seem to be old and unmaintained.
They also break on some python versions on travis.

We need to find replacements for them.

**Comment by IwanVosloo** [comment]
Possible contenders:
https://github.com/ndparker/rjsmin
https://github.com/ndparker/rcssmin

**Comment by IwanVosloo** [comment]
Also:
https://github.com/tikitu/jsmin/

**Comment by craig-reahl** [comment]
https://github.com/sprymix/csscompressor

**Comment by craig-reahl** [comment]
https://github.com/juancarlospaco/css-html-js-minify

**Comment by IwanVosloo** [comment]
Fixed in #337
