### ISSUE TITLE
reahl listexaxmples lists files inside examples

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#354]
Since we removed .reahlproject, reahl listexamples does this:

> $ reahl listexamples 
> features.carousel.carousel
> features.carousel.etc.web.config
> features.i18nexample.i18nexample
> features.i18nexample.etc.web.config
> features.validation.validation
> features.validation.etc.web.config
> features.tabbedpanel.tabbedpanel

The issue is that it is looking for a .reahlpoject file in the root of each example which is not there anymore.
It should rather look for a setup.cfg now.

**Comment by craig-reahl** [comment]
See https://github.com/craig-reahl/reahl/tree/craig-listexamples-354
and

https://github.com/reahl/reahl/pull/356

**Comment by IwanVosloo** [comment]
Fixed in #356
