### ISSUE TITLE
Performance enhancements to consider

### ISSUE THREAD

**Issue by craig-reahl** [reahl/reahl#359]
### UrlBoundView :

needs memoized on construction_client_side_state_as_dict_of_lists

```
    @property
    @memoized
    def construction_client_side_state_as_dict_of_lists(self):
```

### ExecutionContext:

add config to switch between thread_local and inspect.getcurrentframe() implementation for

```
get_context
```

### Config to remove runtime checks like:

```
@argchecks
```

optionally also: 

```
check_form_related_programmer_errors
```

**Comment by IwanVosloo** [comment]
The agchecks bit seems to be what is talked about in #358

**Comment by craig-reahl** [comment]
The method mentioned above cannot be memoized:

```
@memoized
get_interface_locale
```

**Comment by craig-reahl** [comment]
Changes made. Needs merge request
