### ISSUE TITLE
Optimise queries for input state

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#365]
We do a database query to populate each input upon each request.
This results in many queries. We can reduce this to one query that hits the DB once to get the results for all inputs which should improve performance for large forms.

One idea is to query for all SessionData at the beginning of a request, and then caching that for the duration of  request . The cached info can then be used to get values for each input, eg.

**Comment by craig-reahl** [comment]
Decided to store the SessionData on each UrlBoundView
