### ISSUE TITLE
It looks like in-memory SQLite DBs do not create their tables upon connecting

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#366]

**Comment by craig-reahl** [comment]
When a  SQLite :memory: connection type is used, the Reahl development web server creates the database tables as required upon startup. Other connection types require users to create the tables themselves before, using 
`reahl createdbtables etc`

I found that when starting the Reahl development web server, the tables are indeed created. The next call to the database, such as refreshing the the browser that hits the web server, does not get the already setup :memory: database instance from the connection pool.

According to: https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#threading-pooling-behavior
the default connection pool for :memory: type SQLite connections is [SingletonThreadPool](https://docs.sqlalchemy.org/en/14/core/pooling.html#sqlalchemy.pool.SingletonThreadPool). 

Even though only one thread is being used in the Reahl development web server,  it seems the default SingletonThreadPool  for :memory: SQLite connections causes the reported issue when combined with the Reahl development web server.

A workaround is to use the recommended [StaticPool](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#using-a-memory-database-in-multiple-threads) when creating the engine for :memory: connection SQLite connection types:

`create_engine(config.reahlsystem.connection_uri, **create_args, poolclass=StaticPool)
`
which is used  here:
**reahl.sqlalchemysupport.sqlalchemysupport.SqlAlchemyControl**:
```
def connect(self, auto_commit):
...
    self.engine = create_engine(config.reahlsystem.connection_uri, **create_args, poolclass=StaticPool)
...
```

Note: Even the default for most other connection types, QueuePool seems to work also.
