### ISSUE TITLE
Error while trying to install dependacies for hello example

### ISSUE THREAD

**Issue by ronnzw** [reahl/reahl#414]
I'm trying out Reahl, I successfully installed Reahl with [docs, dev, sqlite]. However when trying to install dependencies for the hello examples which is in tutorial.hello, its giving the below error. 
<img width="1010" alt="Screenshot 2023-11-02 at 12 22 41" src="https://github.com/reahl/reahl/assets/17087071/3aa1dceb-32da-4721-b4a9-d37c39c004eb">

**Additional info**
- I'm running python 3.12.  
- I'm getting a warning around ServeSMTP because of a missing module 'asyncore'
- I'm new to Reahl

**Comment by IwanVosloo** [comment]
Hi Ron,

Can you please provide some more details:

Which OS platform are you running on?
Can you also post the directory listing of the hello folder?

Also (although I don't think that will cause this particular error), note that we only support Python 3.6 and onwards; see: https://www.reahl.org/docs/7.0/tutorial/gettingstarted-develop.d.html

Thanks!

**Comment by ronnzw** [comment]
Os: MacOS Sonoma 14.0
Python version: Mine is 3.12.0 which is the latest version.
Directory structure:
<img width="693" alt="Screenshot 2023-11-02 at 13 45 08" src="https://github.com/reahl/reahl/assets/17087071/ef742f5f-48cd-4822-aaee-b506b2bc7ae3">

**Comment by hendrikdutoit** [comment]
Hello Ron
I think you have started your project on Reahl 6.?.  You recently upgraded/reinstalled your environment and it installed (maybe by accident) Reahl 7.0.  Some of you configuration is still in setup.cfg. With my little knowledge that I have about Reahl  7.0, it does not support setup.cfg and it has to be migrated to the pyproject.toml.  If I am right with my diagnosis, you have one of two choices:
1. Revert back to Reahl 6.? 
or
3. Upgrade your configuration to Reahl 7.0

**Comment by ronnzw** [comment]
> Hello Ron I think you have started your project on Reahl 6.?. You recently upgraded/reinstalled your environment and it installed (maybe by accident) Reahl 7.0. Some of you configuration is still in setup.cfg. With my little knowledge that I have about Reahl 7.0, it does not support setup.cfg and it has to be migrated to the pyproject.toml. If I am right with my diagnosis, you have one of two choices:
> 
> 1. Revert back to Reahl 6.?
>    or
> 2. Upgrade your configuration to Reahl 7.0

I just install what is available on `pip install`. Do you have an idea of how l check the version l tried `Reahl --version` it didn't work.

**Comment by IwanVosloo** [comment]
Hi Ron,

Aaah, sorry, I saw the .12 and "read it" as .1!  That version of python should be fine, although we only test up to 3.11.

Yes, @hendrikdutoit is correct, that looks like a hello that was checked out with an older version of reahl.
You do have version 7 installed, because that is the version which will complain about old metadata.

Perhaps just re-checkout the example, overwriting the old one:

reahl example -f tutorial.hello

**Comment by IwanVosloo** [comment]
If you want to know which version of Reahl is installed, you can do:

python -m pip freeze | grep reahl

Perhaps a nicer output also is possible with:

 python -m pip list | grep reahl

**Comment by IwanVosloo** [comment]
With regards to the "reahl servesmtp" problem: I see in https://docs.python.org/3/whatsnew/3.12.html that the asyncore module was removed in python 3.12. We'll have to add support for 3.12. We currently only test for these versions of python:

- 3.8
- 3.9
- 3.10
- 3.11

**Comment by IwanVosloo** [comment]
Added #415

**Comment by ronnzw** [comment]
It looks like l have version 6.

> reahl example -f tutorial.hello

<img width="496" alt="Screenshot 2023-11-02 at 14 22 27" src="https://github.com/reahl/reahl/assets/17087071/3c9a8494-4ef9-4ea2-bf5e-eef96cf291c7">

**Comment by ronnzw** [comment]
> If you want to know which version of Reahl is installed, you can do:
> 
> python -m pip freeze | grep reahl
> 
> Perhaps a nicer output also is possible with:
> 
> python -m pip list | grep reahl

Still getting the same error. I can confirm that l have Reahl version 6.1.1.

**Comment by IwanVosloo** [comment]
Hi Ron,

Somehow if you follow our instructions it installs 6.1.1 instead of 7.0.0. We're investigating....

**Comment by IwanVosloo** [comment]
Hi Ron,

Ok, thanks.... so we found a bug with the packaging that is triggered by the usual install.

To work around it for now (for your selection), do the following after having installed it as you did:

python -m pip install -U reahl  reahl-doc reahl-dev reahl-webdev reahl-stubble reahl-tofu reahl-browsertools reahl-sqlitesupport

**Comment by IwanVosloo** [comment]
What triggers the bug, is the inclusion of dev in the command:

pip install reahl[dev]

The 'dev' extra references reahl-webdriver which was renamed to reahl-browsertools some time ago and thus does not exist in version 7

Installing using other extras should work fine, including:

pip install reahl[all]

**Comment by ronnzw** [comment]
Yes, it's fixed. Thank you.

**Comment by ronnzw** [comment]
@IwanVosloo I'm now failing to run the server should l open a new issue or keep it here?

**Comment by IwanVosloo** [comment]
Hey @ronnzw , are you still on Python 3.12?

**Comment by ronnzw** [comment]
> Hey @ronnzw , are you still on Python 3.12?

I ended up using version 3.10.10 and everything is working.
