### ISSUE TITLE
Code cleanup for move from bzr/launchpad to git/github

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#43]
We want to move from launchpad/bzr to github/git because git/github is familiar to more people.

This includes changing code that makes use of bzr to let us build releases (tagging them in bzr), etc. We need to clean this up and base all that on git. This also includes getting rid of the setuptools plugin in reahl-bzrsupport to be able to use bzr to determine which files to include in an egg etc.

**Comment by IwanVosloo** [comment]
Implemented some of what is needed on https://github.com/IwanVosloo/reahl/tree/bzr-cleanup 

TODO: There's duplicated code (Executable) in bzrsupport that used to be duplicated because we did not want bzrsupport to have any dependencies. We can make reahl-bzrsupport dependent on reahl-component now and nuke the duplication.

**Comment by craig-reahl** [comment]
Implemented and checked it into [bzr-cleanup branch](https://github.com/IwanVosloo/reahl/tree/bzr-cleanup:) 

> TODO: There's duplicated code (Executable) in bzrsupport that used to be duplicated because we did not want bzrsupport to have any dependencies. We can make reahl-bzrsupport dependent on reahl-component now and nuke the duplication.
