### ISSUE TITLE
Upgrade jquery validate

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#51]
We're using a fairly old version of jquery-validate. It needs to be upgraded. 

However this is not a simple task. We have heavily edited the code of the jquery validate version that we ship, mainly to support form-associated inputs, but also to fix various other things. These patches would have to be applied on the new version or tried to get in upstream.

We use the metadata plugin to provide messages related to validation rules. This has been deprecated and now is no longer supported at all in the newer jquery-validate. It means we need to generate html for inputs differently  - we can no longer put validation messages in the class= of an element.

**Comment by craig-reahl** [comment]
Managed to upgrade my fork of reahl to use [jquery-validate](https://github.com/jzaefferer/jquery-validation) 1.15.0, utilising the data-rule-\* and data-msg-\* way of adding custom validations and messages.
Dropped the jquery-metadata dependency.
Had to again modify our copy of jquery validate original source code to be able to cater for elements outside the form tag, which are "linked" to the form by the form attribute, among other things.

Will create a pull request soon.
