### ISSUE TITLE
Remove left-over stuff deprecated in previous versions

### ISSUE THREAD

**Issue by IwanVosloo** [reahl/reahl#57]
I spotted that PrimitiveInput still supports the old deprecated method name "create_html_input". We need to nuke this in 4.0. ... and perhaps look for more 'DEPRECATED' strings in the source code. (This one was done without our decorator.)

**Comment by craig-reahl** [comment]
DONE: Remove from eggs.py: 

-  find_attachments(self, label) and two classes referenced in it: Attachment, EntryPointKeyEncodedAttachmentName
- remove roles_to_add() and out of tests

DONE: Remove concept of DebianPackageSet

**Comment by craig-reahl** [comment]
DONE: Look at deprecated inspect.getargspec.[ Issues with backporting to 2.7](https://github.com/praw-dev/praw/issues/541)
