### ISSUE TITLE
CheckBoxInput must be able to work with ChoiceField

### ISSUE THREAD

**Issue by craig-reahl** [reahl/reahl#77]
CheckBoxInput must be able to work with ChoiceField too.
It alreadys works with BooleanField.

.: If CheckBoxInput is linked to ChoiceField, then it should work like RadioButtonInput which returns an instance of something that represents the users selection. However, it should allow multiple results unlike RadionButtonInput that only returns a single item.

**Comment by craig-reahl** [comment]
Merge request #82

**Comment by IwanVosloo** [comment]
Done in #82
